"""hash

Revision ID: afe0bdcb2726
Revises: 42faa030a8de
Create Date: 2017-04-22 20:38:24.345232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe0bdcb2726'
down_revision = '42faa030a8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.TEXT(), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
